/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_model_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s1[465] = {21, 21, 0, 21, 42, 63, 84, 105, 126, 147, 168, 189, 210, 231, 252, 273, 294, 315, 336, 357, 378, 399, 420, 441, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s2[157] = {21, 7, 0, 21, 42, 63, 84, 105, 126, 147, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s3[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s4[67] = {63, 1, 0, 63, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62};
static const casadi_int casadi_s5[32] = {28, 1, 0, 28, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};
static const casadi_int casadi_s6[410] = {406, 1, 0, 406, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405};

/* ocp_model_expl_ode_hess:(i0[21],i1[21x21],i2[21x7],i3[21],i4[7],i5[63])->(o0[28],o1[406]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[5]? arg[5][6] : 0;
  a1=arg[3]? arg[3][20] : 0;
  a0=(a0*a1);
  a2=arg[5]? arg[5][5] : 0;
  a3=arg[3]? arg[3][19] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[5]? arg[5][4] : 0;
  a4=arg[3]? arg[3][18] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[5]? arg[5][3] : 0;
  a5=arg[3]? arg[3][17] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[5]? arg[5][2] : 0;
  a6=arg[3]? arg[3][16] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[5]? arg[5][1] : 0;
  a7=arg[3]? arg[3][15] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[5]? arg[5][0] : 0;
  a8=arg[3]? arg[3][14] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[5]? arg[5][13] : 0;
  a0=(a0*a1);
  a2=arg[5]? arg[5][12] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[5]? arg[5][11] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[5]? arg[5][10] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[5]? arg[5][9] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[5]? arg[5][8] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[5]? arg[5][7] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[5]? arg[5][20] : 0;
  a0=(a0*a1);
  a2=arg[5]? arg[5][19] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[5]? arg[5][18] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[5]? arg[5][17] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[5]? arg[5][16] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[5]? arg[5][15] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[5]? arg[5][14] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[5]? arg[5][27] : 0;
  a0=(a0*a1);
  a2=arg[5]? arg[5][26] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[5]? arg[5][25] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[5]? arg[5][24] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[5]? arg[5][23] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[5]? arg[5][22] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[5]? arg[5][21] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[5]? arg[5][34] : 0;
  a0=(a0*a1);
  a2=arg[5]? arg[5][33] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[5]? arg[5][32] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[5]? arg[5][31] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[5]? arg[5][30] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[5]? arg[5][29] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[5]? arg[5][28] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[5]? arg[5][41] : 0;
  a0=(a0*a1);
  a2=arg[5]? arg[5][40] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[5]? arg[5][39] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[5]? arg[5][38] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[5]? arg[5][37] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[5]? arg[5][36] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[5]? arg[5][35] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[5]? arg[5][48] : 0;
  a0=(a0*a1);
  a1=arg[5]? arg[5][47] : 0;
  a1=(a1*a3);
  a0=(a0+a1);
  a1=arg[5]? arg[5][46] : 0;
  a1=(a1*a4);
  a0=(a0+a1);
  a1=arg[5]? arg[5][45] : 0;
  a1=(a1*a5);
  a0=(a0+a1);
  a1=arg[5]? arg[5][44] : 0;
  a1=(a1*a6);
  a0=(a0+a1);
  a1=arg[5]? arg[5][43] : 0;
  a1=(a1*a7);
  a0=(a0+a1);
  a1=arg[5]? arg[5][42] : 0;
  a1=(a1*a8);
  a0=(a0+a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=0.;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  a1=arg[3]? arg[3][7] : 0;
  if (res[0]!=0) res[0][14]=a1;
  a1=arg[3]? arg[3][8] : 0;
  if (res[0]!=0) res[0][15]=a1;
  a1=arg[3]? arg[3][9] : 0;
  if (res[0]!=0) res[0][16]=a1;
  a1=arg[3]? arg[3][10] : 0;
  if (res[0]!=0) res[0][17]=a1;
  a1=arg[3]? arg[3][11] : 0;
  if (res[0]!=0) res[0][18]=a1;
  a1=arg[3]? arg[3][12] : 0;
  if (res[0]!=0) res[0][19]=a1;
  a1=arg[3]? arg[3][13] : 0;
  if (res[0]!=0) res[0][20]=a1;
  a1=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][21]=a1;
  a1=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][22]=a1;
  a1=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][23]=a1;
  a1=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][24]=a1;
  a1=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][25]=a1;
  a1=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][26]=a1;
  a1=arg[3]? arg[3][6] : 0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  if (res[1]!=0) res[1][10]=a0;
  if (res[1]!=0) res[1][11]=a0;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a0;
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a0;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a0;
  if (res[1]!=0) res[1][18]=a0;
  if (res[1]!=0) res[1][19]=a0;
  if (res[1]!=0) res[1][20]=a0;
  if (res[1]!=0) res[1][21]=a0;
  if (res[1]!=0) res[1][22]=a0;
  if (res[1]!=0) res[1][23]=a0;
  if (res[1]!=0) res[1][24]=a0;
  if (res[1]!=0) res[1][25]=a0;
  if (res[1]!=0) res[1][26]=a0;
  if (res[1]!=0) res[1][27]=a0;
  if (res[1]!=0) res[1][28]=a0;
  if (res[1]!=0) res[1][29]=a0;
  if (res[1]!=0) res[1][30]=a0;
  if (res[1]!=0) res[1][31]=a0;
  if (res[1]!=0) res[1][32]=a0;
  if (res[1]!=0) res[1][33]=a0;
  if (res[1]!=0) res[1][34]=a0;
  if (res[1]!=0) res[1][35]=a0;
  if (res[1]!=0) res[1][36]=a0;
  if (res[1]!=0) res[1][37]=a0;
  if (res[1]!=0) res[1][38]=a0;
  if (res[1]!=0) res[1][39]=a0;
  if (res[1]!=0) res[1][40]=a0;
  if (res[1]!=0) res[1][41]=a0;
  if (res[1]!=0) res[1][42]=a0;
  if (res[1]!=0) res[1][43]=a0;
  if (res[1]!=0) res[1][44]=a0;
  if (res[1]!=0) res[1][45]=a0;
  if (res[1]!=0) res[1][46]=a0;
  if (res[1]!=0) res[1][47]=a0;
  if (res[1]!=0) res[1][48]=a0;
  if (res[1]!=0) res[1][49]=a0;
  if (res[1]!=0) res[1][50]=a0;
  if (res[1]!=0) res[1][51]=a0;
  if (res[1]!=0) res[1][52]=a0;
  if (res[1]!=0) res[1][53]=a0;
  if (res[1]!=0) res[1][54]=a0;
  if (res[1]!=0) res[1][55]=a0;
  if (res[1]!=0) res[1][56]=a0;
  if (res[1]!=0) res[1][57]=a0;
  if (res[1]!=0) res[1][58]=a0;
  if (res[1]!=0) res[1][59]=a0;
  if (res[1]!=0) res[1][60]=a0;
  if (res[1]!=0) res[1][61]=a0;
  if (res[1]!=0) res[1][62]=a0;
  if (res[1]!=0) res[1][63]=a0;
  if (res[1]!=0) res[1][64]=a0;
  if (res[1]!=0) res[1][65]=a0;
  if (res[1]!=0) res[1][66]=a0;
  if (res[1]!=0) res[1][67]=a0;
  if (res[1]!=0) res[1][68]=a0;
  if (res[1]!=0) res[1][69]=a0;
  if (res[1]!=0) res[1][70]=a0;
  if (res[1]!=0) res[1][71]=a0;
  if (res[1]!=0) res[1][72]=a0;
  if (res[1]!=0) res[1][73]=a0;
  if (res[1]!=0) res[1][74]=a0;
  if (res[1]!=0) res[1][75]=a0;
  if (res[1]!=0) res[1][76]=a0;
  if (res[1]!=0) res[1][77]=a0;
  if (res[1]!=0) res[1][78]=a0;
  if (res[1]!=0) res[1][79]=a0;
  if (res[1]!=0) res[1][80]=a0;
  if (res[1]!=0) res[1][81]=a0;
  if (res[1]!=0) res[1][82]=a0;
  if (res[1]!=0) res[1][83]=a0;
  if (res[1]!=0) res[1][84]=a0;
  if (res[1]!=0) res[1][85]=a0;
  if (res[1]!=0) res[1][86]=a0;
  if (res[1]!=0) res[1][87]=a0;
  if (res[1]!=0) res[1][88]=a0;
  if (res[1]!=0) res[1][89]=a0;
  if (res[1]!=0) res[1][90]=a0;
  if (res[1]!=0) res[1][91]=a0;
  if (res[1]!=0) res[1][92]=a0;
  if (res[1]!=0) res[1][93]=a0;
  if (res[1]!=0) res[1][94]=a0;
  if (res[1]!=0) res[1][95]=a0;
  if (res[1]!=0) res[1][96]=a0;
  if (res[1]!=0) res[1][97]=a0;
  if (res[1]!=0) res[1][98]=a0;
  if (res[1]!=0) res[1][99]=a0;
  if (res[1]!=0) res[1][100]=a0;
  if (res[1]!=0) res[1][101]=a0;
  if (res[1]!=0) res[1][102]=a0;
  if (res[1]!=0) res[1][103]=a0;
  if (res[1]!=0) res[1][104]=a0;
  if (res[1]!=0) res[1][105]=a0;
  if (res[1]!=0) res[1][106]=a0;
  if (res[1]!=0) res[1][107]=a0;
  if (res[1]!=0) res[1][108]=a0;
  if (res[1]!=0) res[1][109]=a0;
  if (res[1]!=0) res[1][110]=a0;
  if (res[1]!=0) res[1][111]=a0;
  if (res[1]!=0) res[1][112]=a0;
  if (res[1]!=0) res[1][113]=a0;
  if (res[1]!=0) res[1][114]=a0;
  if (res[1]!=0) res[1][115]=a0;
  if (res[1]!=0) res[1][116]=a0;
  if (res[1]!=0) res[1][117]=a0;
  if (res[1]!=0) res[1][118]=a0;
  if (res[1]!=0) res[1][119]=a0;
  if (res[1]!=0) res[1][120]=a0;
  if (res[1]!=0) res[1][121]=a0;
  if (res[1]!=0) res[1][122]=a0;
  if (res[1]!=0) res[1][123]=a0;
  if (res[1]!=0) res[1][124]=a0;
  if (res[1]!=0) res[1][125]=a0;
  if (res[1]!=0) res[1][126]=a0;
  if (res[1]!=0) res[1][127]=a0;
  if (res[1]!=0) res[1][128]=a0;
  if (res[1]!=0) res[1][129]=a0;
  if (res[1]!=0) res[1][130]=a0;
  if (res[1]!=0) res[1][131]=a0;
  if (res[1]!=0) res[1][132]=a0;
  if (res[1]!=0) res[1][133]=a0;
  if (res[1]!=0) res[1][134]=a0;
  if (res[1]!=0) res[1][135]=a0;
  if (res[1]!=0) res[1][136]=a0;
  if (res[1]!=0) res[1][137]=a0;
  if (res[1]!=0) res[1][138]=a0;
  if (res[1]!=0) res[1][139]=a0;
  if (res[1]!=0) res[1][140]=a0;
  if (res[1]!=0) res[1][141]=a0;
  if (res[1]!=0) res[1][142]=a0;
  if (res[1]!=0) res[1][143]=a0;
  if (res[1]!=0) res[1][144]=a0;
  if (res[1]!=0) res[1][145]=a0;
  if (res[1]!=0) res[1][146]=a0;
  if (res[1]!=0) res[1][147]=a0;
  if (res[1]!=0) res[1][148]=a0;
  if (res[1]!=0) res[1][149]=a0;
  if (res[1]!=0) res[1][150]=a0;
  if (res[1]!=0) res[1][151]=a0;
  if (res[1]!=0) res[1][152]=a0;
  if (res[1]!=0) res[1][153]=a0;
  if (res[1]!=0) res[1][154]=a0;
  if (res[1]!=0) res[1][155]=a0;
  if (res[1]!=0) res[1][156]=a0;
  if (res[1]!=0) res[1][157]=a0;
  if (res[1]!=0) res[1][158]=a0;
  if (res[1]!=0) res[1][159]=a0;
  if (res[1]!=0) res[1][160]=a0;
  if (res[1]!=0) res[1][161]=a0;
  if (res[1]!=0) res[1][162]=a0;
  if (res[1]!=0) res[1][163]=a0;
  if (res[1]!=0) res[1][164]=a0;
  if (res[1]!=0) res[1][165]=a0;
  if (res[1]!=0) res[1][166]=a0;
  if (res[1]!=0) res[1][167]=a0;
  if (res[1]!=0) res[1][168]=a0;
  if (res[1]!=0) res[1][169]=a0;
  if (res[1]!=0) res[1][170]=a0;
  if (res[1]!=0) res[1][171]=a0;
  if (res[1]!=0) res[1][172]=a0;
  if (res[1]!=0) res[1][173]=a0;
  if (res[1]!=0) res[1][174]=a0;
  if (res[1]!=0) res[1][175]=a0;
  if (res[1]!=0) res[1][176]=a0;
  if (res[1]!=0) res[1][177]=a0;
  if (res[1]!=0) res[1][178]=a0;
  if (res[1]!=0) res[1][179]=a0;
  if (res[1]!=0) res[1][180]=a0;
  if (res[1]!=0) res[1][181]=a0;
  if (res[1]!=0) res[1][182]=a0;
  if (res[1]!=0) res[1][183]=a0;
  if (res[1]!=0) res[1][184]=a0;
  if (res[1]!=0) res[1][185]=a0;
  if (res[1]!=0) res[1][186]=a0;
  if (res[1]!=0) res[1][187]=a0;
  if (res[1]!=0) res[1][188]=a0;
  if (res[1]!=0) res[1][189]=a0;
  if (res[1]!=0) res[1][190]=a0;
  if (res[1]!=0) res[1][191]=a0;
  if (res[1]!=0) res[1][192]=a0;
  if (res[1]!=0) res[1][193]=a0;
  if (res[1]!=0) res[1][194]=a0;
  if (res[1]!=0) res[1][195]=a0;
  if (res[1]!=0) res[1][196]=a0;
  if (res[1]!=0) res[1][197]=a0;
  if (res[1]!=0) res[1][198]=a0;
  if (res[1]!=0) res[1][199]=a0;
  if (res[1]!=0) res[1][200]=a0;
  if (res[1]!=0) res[1][201]=a0;
  if (res[1]!=0) res[1][202]=a0;
  if (res[1]!=0) res[1][203]=a0;
  if (res[1]!=0) res[1][204]=a0;
  if (res[1]!=0) res[1][205]=a0;
  if (res[1]!=0) res[1][206]=a0;
  if (res[1]!=0) res[1][207]=a0;
  if (res[1]!=0) res[1][208]=a0;
  if (res[1]!=0) res[1][209]=a0;
  if (res[1]!=0) res[1][210]=a0;
  if (res[1]!=0) res[1][211]=a0;
  if (res[1]!=0) res[1][212]=a0;
  if (res[1]!=0) res[1][213]=a0;
  if (res[1]!=0) res[1][214]=a0;
  if (res[1]!=0) res[1][215]=a0;
  if (res[1]!=0) res[1][216]=a0;
  if (res[1]!=0) res[1][217]=a0;
  if (res[1]!=0) res[1][218]=a0;
  if (res[1]!=0) res[1][219]=a0;
  if (res[1]!=0) res[1][220]=a0;
  if (res[1]!=0) res[1][221]=a0;
  if (res[1]!=0) res[1][222]=a0;
  if (res[1]!=0) res[1][223]=a0;
  if (res[1]!=0) res[1][224]=a0;
  if (res[1]!=0) res[1][225]=a0;
  if (res[1]!=0) res[1][226]=a0;
  if (res[1]!=0) res[1][227]=a0;
  if (res[1]!=0) res[1][228]=a0;
  if (res[1]!=0) res[1][229]=a0;
  if (res[1]!=0) res[1][230]=a0;
  if (res[1]!=0) res[1][231]=a0;
  if (res[1]!=0) res[1][232]=a0;
  if (res[1]!=0) res[1][233]=a0;
  if (res[1]!=0) res[1][234]=a0;
  if (res[1]!=0) res[1][235]=a0;
  if (res[1]!=0) res[1][236]=a0;
  if (res[1]!=0) res[1][237]=a0;
  if (res[1]!=0) res[1][238]=a0;
  if (res[1]!=0) res[1][239]=a0;
  if (res[1]!=0) res[1][240]=a0;
  if (res[1]!=0) res[1][241]=a0;
  if (res[1]!=0) res[1][242]=a0;
  if (res[1]!=0) res[1][243]=a0;
  if (res[1]!=0) res[1][244]=a0;
  if (res[1]!=0) res[1][245]=a0;
  if (res[1]!=0) res[1][246]=a0;
  if (res[1]!=0) res[1][247]=a0;
  if (res[1]!=0) res[1][248]=a0;
  if (res[1]!=0) res[1][249]=a0;
  if (res[1]!=0) res[1][250]=a0;
  if (res[1]!=0) res[1][251]=a0;
  if (res[1]!=0) res[1][252]=a0;
  if (res[1]!=0) res[1][253]=a0;
  if (res[1]!=0) res[1][254]=a0;
  if (res[1]!=0) res[1][255]=a0;
  if (res[1]!=0) res[1][256]=a0;
  if (res[1]!=0) res[1][257]=a0;
  if (res[1]!=0) res[1][258]=a0;
  if (res[1]!=0) res[1][259]=a0;
  if (res[1]!=0) res[1][260]=a0;
  if (res[1]!=0) res[1][261]=a0;
  if (res[1]!=0) res[1][262]=a0;
  if (res[1]!=0) res[1][263]=a0;
  if (res[1]!=0) res[1][264]=a0;
  if (res[1]!=0) res[1][265]=a0;
  if (res[1]!=0) res[1][266]=a0;
  if (res[1]!=0) res[1][267]=a0;
  if (res[1]!=0) res[1][268]=a0;
  if (res[1]!=0) res[1][269]=a0;
  if (res[1]!=0) res[1][270]=a0;
  if (res[1]!=0) res[1][271]=a0;
  if (res[1]!=0) res[1][272]=a0;
  if (res[1]!=0) res[1][273]=a0;
  if (res[1]!=0) res[1][274]=a0;
  if (res[1]!=0) res[1][275]=a0;
  if (res[1]!=0) res[1][276]=a0;
  if (res[1]!=0) res[1][277]=a0;
  if (res[1]!=0) res[1][278]=a0;
  if (res[1]!=0) res[1][279]=a0;
  if (res[1]!=0) res[1][280]=a0;
  if (res[1]!=0) res[1][281]=a0;
  if (res[1]!=0) res[1][282]=a0;
  if (res[1]!=0) res[1][283]=a0;
  if (res[1]!=0) res[1][284]=a0;
  if (res[1]!=0) res[1][285]=a0;
  if (res[1]!=0) res[1][286]=a0;
  if (res[1]!=0) res[1][287]=a0;
  if (res[1]!=0) res[1][288]=a0;
  if (res[1]!=0) res[1][289]=a0;
  if (res[1]!=0) res[1][290]=a0;
  if (res[1]!=0) res[1][291]=a0;
  if (res[1]!=0) res[1][292]=a0;
  if (res[1]!=0) res[1][293]=a0;
  if (res[1]!=0) res[1][294]=a0;
  if (res[1]!=0) res[1][295]=a0;
  if (res[1]!=0) res[1][296]=a0;
  if (res[1]!=0) res[1][297]=a0;
  if (res[1]!=0) res[1][298]=a0;
  if (res[1]!=0) res[1][299]=a0;
  if (res[1]!=0) res[1][300]=a0;
  if (res[1]!=0) res[1][301]=a0;
  if (res[1]!=0) res[1][302]=a0;
  if (res[1]!=0) res[1][303]=a0;
  if (res[1]!=0) res[1][304]=a0;
  if (res[1]!=0) res[1][305]=a0;
  if (res[1]!=0) res[1][306]=a0;
  if (res[1]!=0) res[1][307]=a0;
  if (res[1]!=0) res[1][308]=a0;
  if (res[1]!=0) res[1][309]=a0;
  if (res[1]!=0) res[1][310]=a0;
  if (res[1]!=0) res[1][311]=a0;
  if (res[1]!=0) res[1][312]=a0;
  if (res[1]!=0) res[1][313]=a0;
  if (res[1]!=0) res[1][314]=a0;
  if (res[1]!=0) res[1][315]=a0;
  if (res[1]!=0) res[1][316]=a0;
  if (res[1]!=0) res[1][317]=a0;
  if (res[1]!=0) res[1][318]=a0;
  if (res[1]!=0) res[1][319]=a0;
  if (res[1]!=0) res[1][320]=a0;
  if (res[1]!=0) res[1][321]=a0;
  if (res[1]!=0) res[1][322]=a0;
  if (res[1]!=0) res[1][323]=a0;
  if (res[1]!=0) res[1][324]=a0;
  if (res[1]!=0) res[1][325]=a0;
  if (res[1]!=0) res[1][326]=a0;
  if (res[1]!=0) res[1][327]=a0;
  if (res[1]!=0) res[1][328]=a0;
  if (res[1]!=0) res[1][329]=a0;
  if (res[1]!=0) res[1][330]=a0;
  if (res[1]!=0) res[1][331]=a0;
  if (res[1]!=0) res[1][332]=a0;
  if (res[1]!=0) res[1][333]=a0;
  if (res[1]!=0) res[1][334]=a0;
  if (res[1]!=0) res[1][335]=a0;
  if (res[1]!=0) res[1][336]=a0;
  if (res[1]!=0) res[1][337]=a0;
  if (res[1]!=0) res[1][338]=a0;
  if (res[1]!=0) res[1][339]=a0;
  if (res[1]!=0) res[1][340]=a0;
  if (res[1]!=0) res[1][341]=a0;
  if (res[1]!=0) res[1][342]=a0;
  if (res[1]!=0) res[1][343]=a0;
  if (res[1]!=0) res[1][344]=a0;
  if (res[1]!=0) res[1][345]=a0;
  if (res[1]!=0) res[1][346]=a0;
  if (res[1]!=0) res[1][347]=a0;
  if (res[1]!=0) res[1][348]=a0;
  if (res[1]!=0) res[1][349]=a0;
  if (res[1]!=0) res[1][350]=a0;
  if (res[1]!=0) res[1][351]=a0;
  if (res[1]!=0) res[1][352]=a0;
  if (res[1]!=0) res[1][353]=a0;
  if (res[1]!=0) res[1][354]=a0;
  if (res[1]!=0) res[1][355]=a0;
  if (res[1]!=0) res[1][356]=a0;
  if (res[1]!=0) res[1][357]=a0;
  if (res[1]!=0) res[1][358]=a0;
  if (res[1]!=0) res[1][359]=a0;
  if (res[1]!=0) res[1][360]=a0;
  if (res[1]!=0) res[1][361]=a0;
  if (res[1]!=0) res[1][362]=a0;
  if (res[1]!=0) res[1][363]=a0;
  if (res[1]!=0) res[1][364]=a0;
  if (res[1]!=0) res[1][365]=a0;
  if (res[1]!=0) res[1][366]=a0;
  if (res[1]!=0) res[1][367]=a0;
  if (res[1]!=0) res[1][368]=a0;
  if (res[1]!=0) res[1][369]=a0;
  if (res[1]!=0) res[1][370]=a0;
  if (res[1]!=0) res[1][371]=a0;
  if (res[1]!=0) res[1][372]=a0;
  if (res[1]!=0) res[1][373]=a0;
  if (res[1]!=0) res[1][374]=a0;
  if (res[1]!=0) res[1][375]=a0;
  if (res[1]!=0) res[1][376]=a0;
  if (res[1]!=0) res[1][377]=a0;
  if (res[1]!=0) res[1][378]=a0;
  if (res[1]!=0) res[1][379]=a0;
  if (res[1]!=0) res[1][380]=a0;
  if (res[1]!=0) res[1][381]=a0;
  if (res[1]!=0) res[1][382]=a0;
  if (res[1]!=0) res[1][383]=a0;
  if (res[1]!=0) res[1][384]=a0;
  if (res[1]!=0) res[1][385]=a0;
  if (res[1]!=0) res[1][386]=a0;
  if (res[1]!=0) res[1][387]=a0;
  if (res[1]!=0) res[1][388]=a0;
  if (res[1]!=0) res[1][389]=a0;
  if (res[1]!=0) res[1][390]=a0;
  if (res[1]!=0) res[1][391]=a0;
  if (res[1]!=0) res[1][392]=a0;
  if (res[1]!=0) res[1][393]=a0;
  if (res[1]!=0) res[1][394]=a0;
  if (res[1]!=0) res[1][395]=a0;
  if (res[1]!=0) res[1][396]=a0;
  if (res[1]!=0) res[1][397]=a0;
  if (res[1]!=0) res[1][398]=a0;
  if (res[1]!=0) res[1][399]=a0;
  if (res[1]!=0) res[1][400]=a0;
  if (res[1]!=0) res[1][401]=a0;
  if (res[1]!=0) res[1][402]=a0;
  if (res[1]!=0) res[1][403]=a0;
  if (res[1]!=0) res[1][404]=a0;
  if (res[1]!=0) res[1][405]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_model_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int ocp_model_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ocp_model_expl_ode_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_model_expl_ode_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_model_expl_ode_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_model_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_model_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
