/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ocp_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[33] = {29, 1, 0, 29, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28};
static const casadi_int casadi_s1[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s2[82] = {78, 1, 0, 78, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77};

/* ocp_model_expl_ode_fun:(i0[29],i1[16],i2[78])->(o0[29]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][4] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][6] : 0;
  a4=(a4*a5);
  a6=sin(a2);
  a7=(a1*a6);
  a8=arg[0]? arg[0][5] : 0;
  a9=sin(a8);
  a10=(a7*a9);
  a11=sin(a0);
  a8=cos(a8);
  a12=(a11*a8);
  a10=(a10-a12);
  a12=arg[0]? arg[0][7] : 0;
  a10=(a10*a12);
  a4=(a4+a10);
  a10=(a11*a9);
  a7=(a7*a8);
  a10=(a10+a7);
  a7=arg[0]? arg[0][8] : 0;
  a10=(a10*a7);
  a4=(a4+a10);
  if (res[0]!=0) res[0][0]=a4;
  a4=(a11*a3);
  a4=(a4*a5);
  a10=(a1*a8);
  a11=(a11*a6);
  a13=(a11*a9);
  a10=(a10+a13);
  a10=(a10*a12);
  a4=(a4+a10);
  a11=(a11*a8);
  a1=(a1*a9);
  a11=(a11-a1);
  a11=(a11*a7);
  a4=(a4+a11);
  if (res[0]!=0) res[0][1]=a4;
  a9=(a3*a9);
  a9=(a9*a12);
  a6=(a6*a5);
  a9=(a9-a6);
  a3=(a3*a8);
  a3=(a3*a7);
  a9=(a9+a3);
  if (res[0]!=0) res[0][2]=a9;
  a9=cos(a0);
  a3=cos(a2);
  a9=(a9*a3);
  a3=arg[0]? arg[0][11] : 0;
  a9=(a9*a3);
  a8=sin(a2);
  a6=arg[0]? arg[0][10] : 0;
  a8=(a8*a6);
  a9=(a9-a8);
  if (res[0]!=0) res[0][3]=a9;
  a9=cos(a2);
  a9=(a9*a6);
  a8=cos(a0);
  a2=sin(a2);
  a8=(a8*a2);
  a8=(a8*a3);
  a9=(a9+a8);
  if (res[0]!=0) res[0][4]=a9;
  a9=arg[0]? arg[0][9] : 0;
  a0=sin(a0);
  a0=(a0*a3);
  a0=(a9-a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[2]? arg[2][0] : 0;
  a8=4.4721359549995798e-01;
  a2=arg[0]? arg[0][15] : 0;
  a4=(a8*a2);
  a11=-4.4721359549995798e-01;
  a1=arg[0]? arg[0][16] : 0;
  a10=(a11*a1);
  a4=(a4+a10);
  a10=arg[0]? arg[0][19] : 0;
  a13=(a8*a10);
  a4=(a4+a13);
  a13=arg[0]? arg[0][20] : 0;
  a14=(a11*a13);
  a4=(a4+a14);
  a14=arg[0]? arg[0][23] : 0;
  a15=(a8*a14);
  a4=(a4+a15);
  a15=arg[0]? arg[0][24] : 0;
  a16=(a11*a15);
  a4=(a4+a16);
  a16=arg[0]? arg[0][27] : 0;
  a17=(a8*a16);
  a4=(a4+a17);
  a17=arg[0]? arg[0][28] : 0;
  a18=(a11*a17);
  a4=(a4+a18);
  a18=arg[2]? arg[2][36] : 0;
  a18=(a18*a5);
  a19=arg[2]? arg[2][42] : 0;
  a19=(a19*a12);
  a18=(a18+a19);
  a19=arg[2]? arg[2][48] : 0;
  a19=(a19*a7);
  a18=(a18+a19);
  a19=arg[2]? arg[2][54] : 0;
  a19=(a19*a9);
  a18=(a18+a19);
  a19=arg[2]? arg[2][60] : 0;
  a19=(a19*a6);
  a18=(a18+a19);
  a19=arg[2]? arg[2][66] : 0;
  a19=(a19*a3);
  a18=(a18+a19);
  a19=arg[2]? arg[2][72] : 0;
  a18=(a18+a19);
  a4=(a4-a18);
  a0=(a0*a4);
  a18=arg[2]? arg[2][6] : 0;
  a19=arg[0]? arg[0][13] : 0;
  a20=(a11*a19);
  a21=arg[0]? arg[0][14] : 0;
  a22=(a8*a21);
  a20=(a20+a22);
  a22=arg[0]? arg[0][17] : 0;
  a23=(a11*a22);
  a20=(a20+a23);
  a23=arg[0]? arg[0][18] : 0;
  a24=(a8*a23);
  a20=(a20+a24);
  a24=arg[0]? arg[0][21] : 0;
  a25=(a11*a24);
  a20=(a20+a25);
  a25=arg[0]? arg[0][22] : 0;
  a26=(a8*a25);
  a20=(a20+a26);
  a26=arg[0]? arg[0][25] : 0;
  a11=(a11*a26);
  a20=(a20+a11);
  a11=arg[0]? arg[0][26] : 0;
  a8=(a8*a11);
  a20=(a20+a8);
  a8=arg[2]? arg[2][37] : 0;
  a8=(a8*a5);
  a27=arg[2]? arg[2][43] : 0;
  a27=(a27*a12);
  a8=(a8+a27);
  a27=arg[2]? arg[2][49] : 0;
  a27=(a27*a7);
  a8=(a8+a27);
  a27=arg[2]? arg[2][55] : 0;
  a27=(a27*a9);
  a8=(a8+a27);
  a27=arg[2]? arg[2][61] : 0;
  a27=(a27*a6);
  a8=(a8+a27);
  a27=arg[2]? arg[2][67] : 0;
  a27=(a27*a3);
  a8=(a8+a27);
  a27=arg[2]? arg[2][73] : 0;
  a8=(a8+a27);
  a20=(a20-a8);
  a18=(a18*a20);
  a0=(a0+a18);
  a18=arg[2]? arg[2][12] : 0;
  a8=8.9442719099991597e-01;
  a27=(a8*a19);
  a28=(a8*a21);
  a27=(a27+a28);
  a28=(a8*a2);
  a27=(a27+a28);
  a28=(a8*a1);
  a27=(a27+a28);
  a28=(a8*a22);
  a27=(a27+a28);
  a28=(a8*a23);
  a27=(a27+a28);
  a28=(a8*a10);
  a27=(a27+a28);
  a28=(a8*a13);
  a27=(a27+a28);
  a28=(a8*a24);
  a27=(a27+a28);
  a28=(a8*a25);
  a27=(a27+a28);
  a28=(a8*a14);
  a27=(a27+a28);
  a28=(a8*a15);
  a27=(a27+a28);
  a28=(a8*a26);
  a27=(a27+a28);
  a28=(a8*a11);
  a27=(a27+a28);
  a28=(a8*a16);
  a27=(a27+a28);
  a8=(a8*a17);
  a27=(a27+a8);
  a8=arg[2]? arg[2][38] : 0;
  a8=(a8*a5);
  a28=arg[2]? arg[2][44] : 0;
  a28=(a28*a12);
  a8=(a8+a28);
  a28=arg[2]? arg[2][50] : 0;
  a28=(a28*a7);
  a8=(a8+a28);
  a28=arg[2]? arg[2][56] : 0;
  a28=(a28*a9);
  a8=(a8+a28);
  a28=arg[2]? arg[2][62] : 0;
  a28=(a28*a6);
  a8=(a8+a28);
  a28=arg[2]? arg[2][68] : 0;
  a28=(a28*a3);
  a8=(a8+a28);
  a28=arg[2]? arg[2][74] : 0;
  a8=(a8+a28);
  a27=(a27-a8);
  a18=(a18*a27);
  a0=(a0+a18);
  a18=arg[2]? arg[2][18] : 0;
  a8=1.3416407864998739e-02;
  a28=(a8*a19);
  a29=4.0249223594996220e-02;
  a30=(a29*a21);
  a28=(a28+a30);
  a30=2.6832815729997479e-02;
  a31=(a30*a2);
  a28=(a28+a31);
  a31=(a30*a1);
  a28=(a28+a31);
  a31=(a8*a22);
  a28=(a28+a31);
  a31=(a29*a23);
  a28=(a28+a31);
  a31=(a30*a10);
  a28=(a28+a31);
  a31=(a30*a13);
  a28=(a28+a31);
  a31=-4.0249223594996220e-02;
  a32=(a31*a24);
  a28=(a28+a32);
  a32=-1.3416407864998739e-02;
  a33=(a32*a25);
  a28=(a28+a33);
  a33=-2.6832815729997479e-02;
  a34=(a33*a14);
  a28=(a28+a34);
  a34=(a33*a15);
  a28=(a28+a34);
  a34=(a31*a26);
  a28=(a28+a34);
  a34=(a32*a11);
  a28=(a28+a34);
  a34=(a33*a16);
  a28=(a28+a34);
  a34=(a33*a17);
  a28=(a28+a34);
  a34=arg[2]? arg[2][39] : 0;
  a34=(a34*a5);
  a35=arg[2]? arg[2][45] : 0;
  a35=(a35*a12);
  a34=(a34+a35);
  a35=arg[2]? arg[2][51] : 0;
  a35=(a35*a7);
  a34=(a34+a35);
  a35=arg[2]? arg[2][57] : 0;
  a35=(a35*a9);
  a34=(a34+a35);
  a35=arg[2]? arg[2][63] : 0;
  a35=(a35*a6);
  a34=(a34+a35);
  a35=arg[2]? arg[2][69] : 0;
  a35=(a35*a3);
  a34=(a34+a35);
  a35=arg[2]? arg[2][75] : 0;
  a34=(a34+a35);
  a28=(a28-a34);
  a18=(a18*a28);
  a0=(a0+a18);
  a18=arg[2]? arg[2][24] : 0;
  a34=(a30*a19);
  a35=(a30*a21);
  a34=(a34+a35);
  a35=(a8*a2);
  a34=(a34+a35);
  a35=(a29*a1);
  a34=(a34+a35);
  a35=(a33*a22);
  a34=(a34+a35);
  a35=(a33*a23);
  a34=(a34+a35);
  a35=(a31*a10);
  a34=(a34+a35);
  a35=(a32*a13);
  a34=(a34+a35);
  a35=(a33*a24);
  a34=(a34+a35);
  a33=(a33*a25);
  a34=(a34+a33);
  a31=(a31*a14);
  a34=(a34+a31);
  a31=(a32*a15);
  a34=(a34+a31);
  a31=(a30*a26);
  a34=(a34+a31);
  a30=(a30*a11);
  a34=(a34+a30);
  a30=(a8*a16);
  a34=(a34+a30);
  a29=(a29*a17);
  a34=(a34+a29);
  a29=arg[2]? arg[2][40] : 0;
  a29=(a29*a5);
  a30=arg[2]? arg[2][46] : 0;
  a30=(a30*a12);
  a29=(a29+a30);
  a30=arg[2]? arg[2][52] : 0;
  a30=(a30*a7);
  a29=(a29+a30);
  a30=arg[2]? arg[2][58] : 0;
  a30=(a30*a9);
  a29=(a29+a30);
  a30=arg[2]? arg[2][64] : 0;
  a30=(a30*a6);
  a29=(a29+a30);
  a30=arg[2]? arg[2][70] : 0;
  a30=(a30*a3);
  a29=(a29+a30);
  a30=arg[2]? arg[2][76] : 0;
  a29=(a29+a30);
  a34=(a34-a29);
  a18=(a18*a34);
  a0=(a0+a18);
  a18=arg[2]? arg[2][30] : 0;
  a19=(a8*a19);
  a21=(a32*a21);
  a19=(a19+a21);
  a2=(a32*a2);
  a19=(a19+a2);
  a1=(a8*a1);
  a19=(a19+a1);
  a22=(a32*a22);
  a19=(a19+a22);
  a23=(a8*a23);
  a19=(a19+a23);
  a10=(a32*a10);
  a19=(a19+a10);
  a13=(a8*a13);
  a19=(a19+a13);
  a24=(a32*a24);
  a19=(a19+a24);
  a25=(a8*a25);
  a19=(a19+a25);
  a14=(a8*a14);
  a19=(a19+a14);
  a15=(a32*a15);
  a19=(a19+a15);
  a26=(a8*a26);
  a19=(a19+a26);
  a11=(a32*a11);
  a19=(a19+a11);
  a8=(a8*a16);
  a19=(a19+a8);
  a32=(a32*a17);
  a19=(a19+a32);
  a32=arg[2]? arg[2][41] : 0;
  a32=(a32*a5);
  a5=arg[2]? arg[2][47] : 0;
  a5=(a5*a12);
  a32=(a32+a5);
  a5=arg[2]? arg[2][53] : 0;
  a5=(a5*a7);
  a32=(a32+a5);
  a5=arg[2]? arg[2][59] : 0;
  a5=(a5*a9);
  a32=(a32+a5);
  a5=arg[2]? arg[2][65] : 0;
  a5=(a5*a6);
  a32=(a32+a5);
  a5=arg[2]? arg[2][71] : 0;
  a5=(a5*a3);
  a32=(a32+a5);
  a5=arg[2]? arg[2][77] : 0;
  a32=(a32+a5);
  a19=(a19-a32);
  a18=(a18*a19);
  a0=(a0+a18);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a0=(a0*a4);
  a18=arg[2]? arg[2][7] : 0;
  a18=(a18*a20);
  a0=(a0+a18);
  a18=arg[2]? arg[2][13] : 0;
  a18=(a18*a27);
  a0=(a0+a18);
  a18=arg[2]? arg[2][19] : 0;
  a18=(a18*a28);
  a0=(a0+a18);
  a18=arg[2]? arg[2][25] : 0;
  a18=(a18*a34);
  a0=(a0+a18);
  a18=arg[2]? arg[2][31] : 0;
  a18=(a18*a19);
  a0=(a0+a18);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[2]? arg[2][2] : 0;
  a0=(a0*a4);
  a18=arg[2]? arg[2][8] : 0;
  a18=(a18*a20);
  a0=(a0+a18);
  a18=arg[2]? arg[2][14] : 0;
  a18=(a18*a27);
  a0=(a0+a18);
  a18=arg[2]? arg[2][20] : 0;
  a18=(a18*a28);
  a0=(a0+a18);
  a18=arg[2]? arg[2][26] : 0;
  a18=(a18*a34);
  a0=(a0+a18);
  a18=arg[2]? arg[2][32] : 0;
  a18=(a18*a19);
  a0=(a0+a18);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[2]? arg[2][3] : 0;
  a0=(a0*a4);
  a18=arg[2]? arg[2][9] : 0;
  a18=(a18*a20);
  a0=(a0+a18);
  a18=arg[2]? arg[2][15] : 0;
  a18=(a18*a27);
  a0=(a0+a18);
  a18=arg[2]? arg[2][21] : 0;
  a18=(a18*a28);
  a0=(a0+a18);
  a18=arg[2]? arg[2][27] : 0;
  a18=(a18*a34);
  a0=(a0+a18);
  a18=arg[2]? arg[2][33] : 0;
  a18=(a18*a19);
  a0=(a0+a18);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[2]? arg[2][4] : 0;
  a0=(a0*a4);
  a18=arg[2]? arg[2][10] : 0;
  a18=(a18*a20);
  a0=(a0+a18);
  a18=arg[2]? arg[2][16] : 0;
  a18=(a18*a27);
  a0=(a0+a18);
  a18=arg[2]? arg[2][22] : 0;
  a18=(a18*a28);
  a0=(a0+a18);
  a18=arg[2]? arg[2][28] : 0;
  a18=(a18*a34);
  a0=(a0+a18);
  a18=arg[2]? arg[2][34] : 0;
  a18=(a18*a19);
  a0=(a0+a18);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[2]? arg[2][5] : 0;
  a0=(a0*a4);
  a4=arg[2]? arg[2][11] : 0;
  a4=(a4*a20);
  a0=(a0+a4);
  a4=arg[2]? arg[2][17] : 0;
  a4=(a4*a27);
  a0=(a0+a4);
  a4=arg[2]? arg[2][23] : 0;
  a4=(a4*a28);
  a0=(a0+a4);
  a4=arg[2]? arg[2][29] : 0;
  a4=(a4*a34);
  a0=(a0+a4);
  a4=arg[2]? arg[2][35] : 0;
  a4=(a4*a19);
  a0=(a0+a4);
  if (res[0]!=0) res[0][11]=a0;
  a0=0.;
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a0;
  a0=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a0;
  a0=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a0;
  a0=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a0;
  a0=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a0;
  a0=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a0;
  a0=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a0;
  a0=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a0;
  a0=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ocp_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ocp_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int ocp_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ocp_model_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_model_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ocp_model_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ocp_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ocp_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
