function h = plotRB(obj, figHandle, T, cones, palm, Fb, Fc)
%PLOTRB Summary of this function goes here
%   Detailed explanation goes here

figHandle;
hold on
axis equal
grid on

h = [];

bottom =   [-1  1 -1; ...
             1  1 -1; ...
             1 -1 -1; ...
            -1 -1 -1]*0.03;

top =      [-1  1  1; ...
             1  1  1; ...
             1 -1  1; ...
            -1 -1  1]*0.03;
        
bottom = (T(1:3,1:3)*bottom' + T(1:3,4))';
top = (T(1:3,1:3)*top' + T(1:3,4))';
        
for i = 1 : size(bottom, 1)-1
    
    h=[h,line([bottom(i, 1), bottom(i+1, 1)], ... 
         [bottom(i, 2), bottom(i+1, 2)], ...
         [bottom(i, 3), bottom(i+1, 3)], ...
         'color', [0 0 0])];
end

    h=[h,line([bottom(4, 1), bottom(1, 1)], ... 
         [bottom(4, 2), bottom(1, 2)], ...
         [bottom(4, 3), bottom(1, 3)], ...
         'color', [0 0 0])];

for i = 1 : size(top, 1)-1
    
    h=[h,line([top(i, 1), top(i+1, 1)], ... 
         [top(i, 2), top(i+1, 2)], ...
         [top(i, 3), top(i+1, 3)], ...
         'color', [0 0 0])];
end

    h=[h,line([top(4, 1), top(1, 1)], ... 
         [top(4, 2), top(1, 2)], ...
         [top(4, 3), top(1, 3)], ...
         'color', [0 0 0])];

for i = 1 : size(bottom, 1)
    
    h=[h,line([bottom(i, 1), top(i, 1)], ... 
         [bottom(i, 2), top(i, 2)], ...
         [bottom(i, 3), top(i, 3)], ...
         'color', [0 0 0])];
end     


if(cones)
   for i = 1 : size(obj.contacts, 2)
       for j = 1 : size(obj.contacts(i).x_hat_, 2)
            l = obj.contacts(i).F_(1:3,4) + 0.03*obj.contacts(i).x_hat_(:,j);
            h = [h, line([l(1) obj.contacts(i).F_(1,4)], ...
                         [l(2) obj.contacts(i).F_(2,4)], ... 
                         [l(3), obj.contacts(i).F_(3,4)], ...
                         'color', [0 1 0])];
       end
   end
end

if(~isempty(Fb))
    h = [h, line([Fb(1), 0], ...
                 [Fb(2), 0], ...
                 [Fb(3), 0], ...
                 'color', [0,0,1], 'LineWidth', 1.5)];
    
    h = [h, line([Fb(4), 0], ...
                 [Fb(5), 0], ...
                 [Fb(6), 0],...
                 'color', [1,0,1], 'LineWidth', 1.5)]; 
end

if(~isempty(Fc))
   for i = 1 : size(obj.contacts, 2)
        l = obj.contacts(i).F_(1:3,4) + 1*Fc((i-1)*3+1:i*3);
        h = [h, line([l(1) obj.contacts(i).F_(1,4)], ...
                     [l(2) obj.contacts(i).F_(2,4)], ... 
                     [l(3), obj.contacts(i).F_(3,4)], ...
                     'color', [1 0 0], 'LineWidth', 1.5)];
   end
end

if(palm)
    
    x = [1 -1 -1 1]*0.1;
    y = [1 1 -1 -1]*0.1;
    z = [-0.03 -0.03 -0.03 -0.03];
    
    P =[x; y; z];
    P = (T(1:3,1:3)*P + T(1:3,4))';
    
    patch('XData',P(:,1),'YData',P(:,2),'ZData',P(:,3),'FaceColor','black','FaceAlpha',.25)
end
end

